DROP INDEX IF EXISTS i_masque ;
DROP INDEX IF EXISTS i_conf ;
DROP INDEX IF EXISTS i_teletra ;
DROP INDEX IF EXISTS i_resid ;
DROP INDEX IF EXISTS i_trav ;
DROP INDEX IF EXISTS i_dist ;
DROP INDEX IF EXISTS i_cas ;
DROP INDEX IF EXISTS i_deces ;
